import { BadRequestError } from "../Errors/BadRequest.error";
import { IProduct } from "../Interfaces/IProduct";
import { Product } from "../Models/Product";

export class ProductRepository {
  // Get all products
  getAllProducts = async (): Promise<IProduct[]> => {
    return await Product.find();
  };

  // Get products by store ID (removed)
  // Removed: getProductsByStoreId

  // Create a new product
  createProduct = async (product: Partial<IProduct>): Promise<IProduct> => {
    const newProduct = new Product({
      code: product.code || undefined, // Ensure a code is generated by Mongoose
      name: product.name,
      director: product.director,
      sinopse: product.sinopse,
      lancamento: product.lancamento,
      rating: [], // Initialize with an empty array
      tags: product.tags,
      image: product.image,
    });

    return await newProduct.save();
  };

  // Update an existing product
  updateProduct = async (
    product: Partial<IProduct>,
    product_code: string
  ): Promise<IProduct> => {
    if (!product_code) throw new BadRequestError("Código é necessário!");

    const updatedProduct = await Product.findOneAndUpdate(
      { code: product_code },
      {
        ...product, // Spread the product properties for update
      },
      {
        new: true,
        runValidators: true,
      }
    );

    if (!updatedProduct) throw new BadRequestError("Produto não encontrado!");

    return updatedProduct;
  };

  // Rate a product
  rateProduct = async (
    product_code: string,
    rate: number
  ): Promise<IProduct> => {
    const product = await Product.findOne({ code: product_code });

    if (!product) throw new BadRequestError("Produto não encontrado!");

    product.rating.push(rate);

    return await product.save();
  };

  // Delete a product
  deleteProduct = async (product_code: string): Promise<IProduct> => {
    if (!product_code) throw new BadRequestError("Código é necessário!");

    const deletedProduct = await Product.findOneAndDelete({
      code: product_code,
    });

    if (!deletedProduct) throw new BadRequestError("Produto não encontrado!");

    return deletedProduct;
  };

  // Delete all products
  deleteAll = async (): Promise<void> => {
    await Product.deleteMany().exec();
  };
}
